name: R Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, python-path: ${{ github.workspace }}/venv/bin/python }
          - { os: windows-latest, python-path: ${{ github.workspace }}\\venv\\Scripts\\python.exe }
          - { os: macos-latest, python-path: ${{ github.workspace }}/venv/bin/python }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RETICULATE_PYTHON: ${{ matrix.config.python-path }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: sudo apt-get install -y python3 python3-venv python3-pip

    - name: Set up Python virtual environment on Ubuntu
      if: runner.os == 'Linux'
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install numpy pandas # Add any additional Python packages needed by reticulate or your package

    - name: Install Python on Windows
      if: runner.os == 'Windows'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set up Python virtual environment on Windows
      if: runner.os == 'Windows'
      run: |
        python -m venv venv
        .\\venv\\Scripts\\activate
        pip install --upgrade pip
        pip install numpy pandas # Add any additional Python packages needed by reticulate or your package

    - name: Set up Python virtual environment on macOS
      if: runner.os == 'macOS'
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install numpy pandas # Add any additional Python packages needed by reticulate or your package

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'remotes::install_cran("reticulate")'
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Check package
      uses: r-lib/actions/check-r-package@v2
      with:
        error-on-warning: true

    - name: Upload check results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: R-CMD-check-results
        path: check

    # - name: Save Python virtual environment on Ubuntu
    #   if: runner.os == 'Linux'
    #   uses: actions/cache@v2
    #   with:
    #     path: venv
    #     key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-python-
    # 
    # - name: Save Python virtual environment on Windows
    #   if: runner.os == 'Windows'
    #   uses: actions/cache@v2
    #   with:
    #     path: venv
    #     key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-python-
    # 
    # - name: Save Python virtual environment on macOS
    #   if: runner.os == 'macOS'
    #   uses: actions/cache@v2
    #   with:
    #     path: venv
    #     key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-python-
