# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: MacOS-Check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: OS=${{ matrix.config.os }} R=${{ matrix.config.r }} py=${{ matrix.config.python }}

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest  , r: 'release', python: '3.10' }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      PYTORCH_MPS_HIGH_WATERMARK_RATIO: '0.0'

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: actions/setup-python@v4
        if: matrix.config.python != 'debug'
        with:
          python-version: ${{ matrix.config.python }}

      - if: matrix.config.python == 'debug'
        name: setup python3-dbg
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dbg python3-pip python3-venv
          sudo ln -sf /usr/bin/python3-dbg /usr/bin/python3
          sudo ln -sf /usr/bin/python3-dbg /usr/bin/python

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck local::.
          cache-version: 4
          upgrade: 'TRUE'

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.config.python }}
          activate-environment: r-reticulate

      - name: Install reticulate and set up conda environment
        shell: Rscript {0}
        run: |
          install.packages("reticulate")
          reticulate::install_miniconda()
          reticulate::py_install('DeepForest', pip=TRUE)
          library(reticulate)
          conda_create("r-reticulate")
          conda_install("r-reticulate", "numpy", pip=TRUE)
          use_condaenv("r-reticulate")

      - name: Run R CMD check
        run: |
          echo "RETICULATE_PYTHON=$(python -c 'import sys; print(sys.executable)')" >> $GITHUB_ENV
          R CMD check --no-manual --as-cran
        shell: bash

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: --no-manual --as-cran
