# R package release checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check-release

jobs:
  R-CMD-check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CRAN_REPO: https://packagemanager.rstudio.com/all/__linux__/focal/latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup R (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: eddelbuettel/github-actions/r2u-setup@master
      - name: Setup R (Other)
        if: matrix.os != 'ubuntu-latest'
        uses: r-lib/actions/setup-r@v2
      - name: Install package dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "reticulate"))
          remotes::install_deps(dependencies = TRUE, repos = c("CRAN" = Sys.getenv("CRAN_REPO")))
        shell: Rscript {0}
      - name: Install DeepForest
        run: |
          library("reticulate")
          conda_create("r-reticulate")
          conda_install("r-reticulate", "DeepForest", pip=TRUE)
          use_condaenv("r-reticulate")
        shell: Rscript {0}
      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}