name: Test R Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [ '4.2.3', '4.3.1' ]
        python-version: [ '3.9', '3.11' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "testthat", "reticulate"), repos="https://cran.r-project.org")
          remotes::install_cran("devtools", dependencies=TRUE)
        shell: Rscript {0}

      - name: Install deepforest Python package
        run: |
          pip install deepforest

      - name: Test deepforest
        run: |
          library(devtools)
          library(testthat)
          library(reticulate)
          test()
        shell: Rscript {0}
