name: R Package Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        r-version: ["4.2", "4.3"]
        python-version: ["3.9", "3.11"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages(c("devtools", "testthat", "reticulate"))'
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'
      
      - name: Install Python package Deepforest
        run: |
          python -m pip install --upgrade pip
          pip install deepforest
      
      - name: Verify Python installation in R
        run: |
          Rscript -e 'reticulate::py_config()'
      
      - name: Run R package tests
        run: |
          Rscript -e 'devtools::test()'
